name: cblpython
channels:
  - conda-forge
  # - pytorch
  # - fastai
dependencies:
  - python>=3.10
  - pip
  # BASICS
  - numpy
  - scipy
  - pandas
  - tqdm
  - click
  - ipython
  # VISUALIZATION
  - matplotlib
  - ipympl  # interactive matplotlib plots
  - seaborn
  # - altair
  # - yellowbrick
  # ML, STATS & DEEP LEARNING
  # - statsmodels
  # - scikit-learn
  # - sktime
  # - tslearn
  # - xgboost
  # - catboost
  # - lightgbm
  # - pytorch
  # - fastai  # activate fastai channel above!
  # - tensorflow
  # - keras
  # - spacy
  # OTHER TOOLS
  # - optuna
  # - dask
  # - snakeviz
  - pip:
    - -e .  # install git checkout of cblpython in editable mode
    - pyvista[io,jupyter]  # pyvista is a 2D visualization library for Python
    # add here only pip-packages that are not available in conda/conda-forge! E.g.:
    # - icecream
    # - jax
    # - numpyro
    # - funsor
    # - neptune-client
    # - neptune-contrib

  # DEVELOPMENT ONLY PACKAGES (Consider using pipx to install these packages globally)
  - jupyterlab
  - pytest
  - pytest-cov
  - tox
  - pre_commit
  - nbdime
  - nbstripout
  - sphinx
  - recommonmark
